### ISSUE TITLE
[RFE] Make Network Configuration an Array

### ISSUE THREAD

**Issue by shabazzfsher** [ranchergovernment/rancher-cluster-templates#12]
#Feature Request

Request description:
Customer requests that Network configuration be structured as an array.

Example:
```
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: nc-vsphere-master-config
  namespace: fleet-default
network:
- /Example/VM-Network
os: linux
cfgparam:
- disk.enableUUID=TRUE
```
