### ISSUE TITLE
Deploy Monitoring through Apps - Issue : page not found

### ISSUE THREAD

**Issue by seb-835** [ranchergovernment/rancher-cluster-templates#67]
Hi Team,

when i install the Monitoring apps throught Rancher Management UI :
all goes fine, i reach Grafana through Monitoring-> Grafana and i got to the home dashboard.

when i install using the managedCharts from the template

```
addons:
  monitoring:
    enabled: true
    version: 105.2.0+up66.7.1-rancher.10
```

Monitoring-> Grafana bring me to the Grafana Page not found :

![Image](https://github.com/user-attachments/assets/463a0007-9214-4e5e-964e-d5c4afbe2a59)

If i click the "home link" on this page then i get the wanted home dashboard.

I have the same behaviour when installing through helm, so i think there is a missing parameters, but can't find which yet.

**Comment by zackbradys** [comment]
hey @seb-835, did you verify that version of the monitoring chart is compatible with the version of Rancher? If you go to a cluster's dashboard, then click `Cluster`, then `Tools`, then `Monitoring`, is that the same version? 

If you are in an airgapped environment do you have all the required images available? Any pods failing or erroring under the `cattle-monitoring-system` namespace?

**Comment by seb-835** [comment]
Hi  @zackbradys ,
yes, exactly the same, i take version from from Rancher UI and all images are available and containers are running in cattle-monitoring-system namespace.
Prometheus/Grafana are working well,   it s just the first redirection from rancher ui to grafana that link to  a not found page...  but as soon as i select home or  a dashboard, all is fine.   

Best.

**Comment by seb-835** [comment]
Hi, in fact this a problem of chicken and eggs,  or making the deployment in 2 pass (downstream then apps).

As for dowstream clusters to avoid the Grafana 404 page not found when reaching through monitoring>grafana, you have to  fill the monitoring value file with : 

```
addons:
  monitoring:
    enabled: true
    version: 105.2.0+up66.7.1-rancher.io
    values:
      global:
        cattle:
          clusterId: xxxx
          clusterName: xxxx
      grafana:
        grafana.ini:
          auth.anonymous:
            org_role: Admin
        sidecar:
          dashboards:
            searchNamespace: ALL
      rke2ControllerManager:
        enabled: true
      rke2Etcd:
        enabled: true
      rke2IngressNginx: 
        enabled: true
      rke2Proxy:
        enabled: true
      rke2Scheduler:
        enabled: true
```
but clusterId is only available after downstream cluster deployment is done and through a human query : 

_kubectl get clusters.management.cattle.io -o json | jq -r '.items[] | select(.spec.displayName == "my-cluster-0") | .metadata.name'_
